"""empty message

Revision ID: 6bd2ac7814ee
Revises: a8a73c4ab610
Create Date: 2026-02-20 16:04:32.808950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6bd2ac7814ee'
down_revision: Union[str, Sequence[str], None] = 'a8a73c4ab610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
